
import './globals.css'
import { Inter } from 'next/font/google'

import { Providers } from '@/Redux/Providers'
import Nav from '@/Component/Nav'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript">  
</script>
      </head>
      <body className={inter.className}>
        <Providers>
          <Nav/>
        {children}
        <ToastContainer autoClose={1000} theme="dark" />
        </Providers>
        </body>
    </html>
  )
}
